INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Ashokapuram','GHPS DEVARAJU URS COLONY','Devarajaurs Colony','Kannada','29261201703');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Kanakagiri','GHPS SHARADAVILAS KANAKAGERE ','Kanakagiri','Kannada','29261201102');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Kanakagiri','GHPS URDU RAHAMANIYA','Rehmaniya','Urdu','29261201602');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Kurubarahalli','GHPS BODYGAURD LINE','Kurubarahalli','Kannada','29261203102');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Ashokapuram','GHS 1ST CROSS ASHOKA PURAM ','Ashokapuram 1st  Cross','Kannada','29261201310');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Kanakagiri','GHPS KRISHNARAJA BB GARDANS','B B Garden','Kannada','29261201003');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Kurubarahalli','GLPS ITTEGE GUD ','Ittigegud','Kannada','29261203207');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Ashokapuram','GHPS HALE KRISHNAMURTHIPURAM','Krishnamurthy','Kannada','29261201319');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Lakshmipuram','GHPS GADI CHOKA LAKSHMIPURAM','Lakshmipuram','Kannada','29261200903');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Ashokapuram','GLPS NELLUR SHED','Nellore Shed','Kannada','29261201501');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Kanakagiri','GHPS URDU BOYS K R MOHALLA','K R Mohalla','Urdu','29261200804');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Kanakagiri','GLPS URDU PILKANA ','Fil Khana','Urdu','29261200721');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Ashokapuram','GHPS, Ashokapuram 13th Cross','Ashokapuram 13th Cross','Kannada','29261201502');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Ashokapuram','GLPS JAYANAGAR','Jayanagar','Kannada','29261201404');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Ashokapuram','GHPS URDU NACHANA HALLI PALYA ','N H Palya','Urdu','29261201801');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Kurubarahalli','GHPS MAHARANI NTMS N S ROAD','Narayanasastry Road, N R Mohalla','Kannada','29261203004');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Kanakagiri','GHPS URDU KRISHNARAJA','Padma Theater','Urdu','29261201004');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Kuduremala','GHPS, Kuduremala','Garlagunji','Kannada','29261202902');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Lakshmipuram','GHPS V.M.V BALA BHODIDI CHAMUNNDIPURAM','VMV Balbodhini','Kannada','29261201201');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Ashokapuram','GHS RAILWAY WORKSHOP ','Railway Workshop','Kannada','29261201506');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Kurubarahalli','GHPS SHIVARAM PET','Devaraja Mohala','Kannada','29261203005');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Lakshmipuram','GHPS THAMIL V.V ROAD ','V V Road','Tamil','29261200904');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Ashokapuram','GHPS PYLAVAN BASAVAIAHNA','Basavaiah','Kannada','29261201405');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Lakshmipuram','GHPS KUKKRAHALLI','Kukkarahalli','Kannada','29261202602');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Kanakagiri','GHPS N.M..K.V.BALABHODINI ','NMK Balbodhini','Kannada','29261200803');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Kanakagiri','GHPS URDU GIRLS K R MOHALLA','K R Mohalla','Urdu','29261200805');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Ashokapuram','GHPS KANNE GOWDANA KOPPAL ','K G Koppal','Kannada','29261201406');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Kanakagiri','GLPS HOSA ITTEGEGUD','Vidyaranyapura','Kannada','29261201606');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Kanakagiri','GLPS MUNESWARA NAGAR','Muneshwar Nagar','Kannada','29261201103');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Kuvempunagar','GHPS KUVEMPUNAGAR','Kuvempunagar','Kannada','29261202402');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Kuvempunagar','GHPS VASANTHANAGAR','Vasanthnagar','Kannada','29261202802');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Kuvempunagar','GULPS VASANTHNAGAR','Vasanth Nagar','Urdu','29261202819');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Kuvempunagar','GHPS THONACHIKOPPAL','Thonachikoppal','Kannada','29261202801');
INSERT INTO tb_school_info values('MYSORE','MYSORE SOUTH','Kurubarahalli','GHPS K.A.R.P BODYGARD LINE ','KARP Bodyguardlane','Kannada','29261203202');
