#!/usr/bin/env python
# replace a string in multiple files

import fileinput
import glob
import sys
import os


filenames = ["preschool_mp_mla.csv","school_mp_mla.csv"]
repldict = { "BASAVANAGAUDI":"BASAVANAGUDI",
"CHAMARJPET":"CHAMARAJPET",
"DASARAHALLI":"T.DASARAHALLI",
"GOVINDRAJNAGAR":"GOVINDRAJ NAGAR",
"HEBBALA":"HEBBAL",
"JAYANAGARA":"JAYANAGAR",
"K R PURAM":"KR PURAM",
"MAHALAKSHMILAYOUT":"MAHALAKSHMI LAYOUT",
"MALESHWARAM":"MALLESHWARAM",
"PULIKESHINAGARA":"PULAKESHINAGAR",
"RAJAJINAGARA":"RAJAJINAGAR",
"RAJARAJESHVARINAGARA":"RAJARAJESWARINAGARA",
"T . DASARAHALLI":"T.DASARAHALLI",
"VIAJAYNAGARA":"VIJAYNAGAR"}

                stext = sys.argv[1]
                rtext = sys.argv[2]
                if len(sys.argv) == 4:
                    path = os.path.join(sys.argv[3], '*')
                    else:
                        path = '*'


                        print 'finding: %s and replacing with: %s' % (stext, rtext)


                        files = glob.glob(path)
                        for line in fileinput.input(files, inplace=1):
                            if stext in line:
                                    line = line.replace(stext, rtext)
                                        sys.stdout.write(line)
