INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'ADUGODI','Ward',147,'S.M.Murugesh Modaliyar','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'AGARAM','Ward',114,'Sarala','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'AGRAHARA DASARAHALLI','Ward',105,'Roopa Devi','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'A NARAYANAPURA','Ward',56,'S.S.Prasad','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'ANJANAPURA','Ward',196,'S.Gangadhar','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'ARAKERE','Ward',193,'A.N.Purushotham','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'ARAMANE NAGARA','Ward',35,'Dr.M.S.Shiva Prasad','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'ATTIGUPPE','Ward',132,'K.Doddanna','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'ATTURU','Ward',3,'K.N.Geetha Shashikumar','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'AZAD NAGAR','Ward',141,'Gowramma','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'BAGALAKUNTE','Ward',14,'B.R.Chandrashekhar','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'BANASAVADI','Ward',27,'A.Kodanda Reddy','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'BANASHANKARI TEMPLE WARD','Ward',180,'Mohammed Ali','JDS');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'BAPUJI NAGAR','Ward',134,'Krishna.V','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'BASAVANAGUDI','Ward',154,'B.S.Sathyanarayana','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'BASAVANAPURA','Ward',53,'K.Poornima','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'BASAVESHWARA NAGAR','Ward',100,'S.H.Padmaraj','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'BEGUR','Ward',192,'M.Srinivas','JDS');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'BELLANDURU','Ward',150,'Babu Reddy.B.P','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'BENNIGANAHALLI','Ward',50,'Dayanand.N','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'BHARATHI NAGAR','Ward',91,'Shakeel Ahmed','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'BILEKHALLI','Ward',188,'M.Roopa Ramesh','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'BINNIPETE','Ward',121,'Srividya','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'BOMMANAHALLI','Ward',175,'Manjunath Reddy B.S','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'BTM LAYOUT','Ward',176,'G.N.R.Babu','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'BYATARAYANAPURA','Ward',7,'Indira','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'BYRASANDRA','Ward',169,'N.Nagaraju','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'CHALAVADIPALYA','Ward',138,'Rekha','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'CHAMRAJAPET','Ward',140,'B.V.Ganesh','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'CHICKPETE','Ward',109,'A.L.Shivakumar','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'CHIKKALSANDRA','Ward',183,'B.S.Venkataswamy Naidu','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'CHOKKASANDRA','Ward',39,'M.Muniswamy','JDS');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'CHOWDESWARI WARD','Ward',2,'K.V. Yashodha','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'COTTONPETE','Ward',120,'Vasanth Kumari','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'C V RAMAN NAGAR','Ward',57,'M.Krishnappa','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'DATTATREYA TEMPLE','Ward',77,'R.S. Sathyanarayana','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'DAYANANDA NAGAR','Ward',97,'Shakeela.M','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'DEEPANJALI NAGAR','Ward',158,'Malathi','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'DEVARA JEEVANAHALLI','Ward',47,'Sampath Raj .R','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'DEVASANDRA','Ward',55,'R.Manjula Devi','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'DHARMARAYA SWAMY TEMPLE','Ward',119,'P.Dhanaraj','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'DODDA BIDARAKALLU','Ward',40,'T.A.Gayathri','JDS');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'DODDA BOMMASANDRA','Ward',10,'M E Pillappa','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'DODDA NEKKUNDI','Ward',85,'Sridhar Reddy','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'DOMLUR','Ward',112,'Geetha Srinivasa Reddy','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'DR. RAJ KUMAR WARD','Ward',106,'Gangabyraiah','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'EJIPURA','Ward',148,'P.M.Saroja','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'GALI ANJENAYA TEMPLE WARD','Ward',157,'B.S.Anand','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'GANDHINAGAR','Ward',94,'S. Nataraj','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'GANESH MANDIR WARD','Ward',165,'L.Govindaraj','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'GANGA NAGAR','Ward',20,'Anand.V','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'GANGENAHALLI','Ward',34,'M.Nagaraj','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'GARUDACHAR PLAYA','Ward',82,'N.Pillappa','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'GAYITHRI NAGAR','Ward',76,'Chethan Gowda','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'GIRINAGAR','Ward',162,'Lalitha.H.S','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'GOTTIGERE','Ward',194,'S.K.Pushpa','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'GOVINDARAJA NAGAR','Ward',104,'Mohan Kumar','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'GURAPPANAPALYA','Ward',171,'Mohammed Rizwan Nawab','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'HAGADUR','Ward',84,'H.A.Srinivas','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'HAL AIRPORT','Ward',87,'Siddalingaiah','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'HALSOOR','Ward',90,'Udayakumar .R','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'HAMPI NAGAR','Ward',133,'R.Chandrashekaraiah','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'HANUMANTH NAGAR','Ward',155,'K.Chandrashekar','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'HBR LAYOUT','Ward',24,'B.Govindaraju','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'HEBBALA','Ward',21,'Jayappa Reddy C.R','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'HEGGANAHALLI','Ward',71,'Govindegowda M.B','Independent');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'HEMMIGEPURA','Ward',198,'Veena Nagaraju','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'HEROHALLI','Ward',72,'A.M.Hanumanthegowda','JDS');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'HMT WARD','Ward',38,'Asha Suresh','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'HOMBEGOWDA NAGARA','Ward',145,'D.Chandrappa','Independent');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'HONGASANDRA','Ward',189,'Sukanda','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'HORAMAVU','Ward',25,'Tejaswini N. Raju','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'HOSAHALLI','Ward',124,'Dr.S.Raju','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'HOSAKEREHALLI','Ward',161,'H.Narayana','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'HOYSALA NAGAR','Ward',80,'Savitha','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'HSR LAYOUT','Ward',174,'Latha.K','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'HUDI','Ward',54,'B.A.Basavraju','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'JAGAJIVANARAMNAGAR','Ward',136,'Seema Khanum','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'JAKKASANDRA','Ward',173,'Saraswathamma','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'JAKKURU','Ward',5,'Muneendra kumar K.V','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'JALAHALLI','Ward',16,'R. Narayana Swamy','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'JARAGANAHALLI','Ward',186,'Suguna Balakrishna','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'JAYACHAMARAJENDRA NAGAR','Ward',46,'Govindraj N','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'JAYAMAHAL','Ward',63,'M.K.Gunashekar','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'JAYANAGAR','Ward',153,'Gangambike','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'JAYANAGAR EAST','Ward',170,'Muni Sanjeevaiah','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'JEEVANBHIMA NAGAR','Ward',88,'K.Chandrashekhar','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'JNANA BHARATHI WARD','Ward',129,'Govindaraju','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'JOGUPALYA','Ward',89,'M.Goutham kumar','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'J P NAGAR','Ward',177,'N.Chandrashekhar Raju','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'J P PARK','Ward',17,'B.R.Nanjudappa','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'KACHARKANAHALLI','Ward',29,'Padmanabhareddy','JDS');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'KADUGODI','Ward',83,'K.N.Anjaneya Reddy','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'KADUGONDANAHALLI','Ward',30,'Shaheen Taj','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'KADU MALLESHWAR WARD','Ward',65,'G.Manjunath Raju','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'KAMAKSHIPALYA','Ward',101,'K.Ranganna','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'KAMMANAHALLI','Ward',28,'M.C.Srinivas','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'KARISANDRA','Ward',166,'Jyothi Shri Harireddy','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'KATRIGUPPE','Ward',163,'D.Venkatesh Murthy','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'KAVAL BAIRASANDRA','Ward',32,'Y.R.Gowramma','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'KAVERIPURA','Ward',103,'R.Prakash','JDS');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'KEMPAPURA AGRAHARA','Ward',122,'Nirmala','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'KEMPEGOWDA WARD','Ward',1,'Y.N.Ashwatha','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'KENGERI','Ward',159,'R.Anjanappa','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'KODIGEHALLI','Ward',8,'Ashwath Narayana gowda','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'KONANKUNTE','Ward',195,'S.Shashirekha Jayaram','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'KONENA AGRAHARA','Ward',113,'M.Chandrappa Reddy','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'KORAMANGALA','Ward',151,'B.N.Kokila','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'KOTTEGEPALYA','Ward',73,'S.Venkatesh Babu','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'K R MARKET','Ward',139,'G.A.Ashwath Narayan','JDS');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'K R PURAM','Ward',52,'N.Veeranna','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'KUMARASWAMY LAYOUT','Ward',181,'Suresh .H','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'KUSHAL NAGAR','Ward',31,'Noor Jahan','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'KUVEMPU NAGAR','Ward',11,'Yashodamma.K.R','Independent');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'LAGGERE','Ward',69,'Lakshmikantha reddy','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'LAKKASANDRA','Ward',146,'K.Mahesh babu','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'LAKSHMI DEVI NAGAR','Ward',42,'Thimmaraju','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'LINGARAJAPURA','Ward',49,'Lavanya Ganesh Reddy','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'MADIVALA','Ward',172,'B.N.Manjunath Reddy','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'MAHALAKSHIMPURAM','Ward',68,'S.Keshavamurthy','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'MALLASANDRA','Ward',13,'R.P.Shashi','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'MALLESWARAM','Ward',45,'N.Jayapala','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'MANGAMMANAPALYA','Ward',190,'Syed Haseena Taj','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'MANORAYANAPALYA','Ward',33,'Fouzia Begum','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'MARAPPANA PALYA','Ward',44,'Lakshmi','JDS');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'MARATHAHALLI','Ward',86,'Varalakshmi.J','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'MARENAHALLI','Ward',125,'N.Shankuntala','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'MARUTHI MANDIR WARD','Ward',126,'V.Vageesh','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'MARUTHI SEVA NAGAR','Ward',59,'R Rajendran','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'MATTIKERE','Ward',36,'Muniswamy Gowda','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'MUDALAPALYA','Ward',127,'N.Shanthakumari','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'MUNESHWARA NAGAR','Ward',48,'S. Kriya Shailaja','JDS');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'NAGAPURA','Ward',67,'S.Harish','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'NAGARABHAVI','Ward',128,'K.Umesh Shetty','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'NAGAVARA','Ward',23,'Irshad Begum','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'NANDINI LAYOUT','Ward',43,'M.Nagaraj','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'NAYANDAHALLI','Ward',131,'H.S.Rajeshwari','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'NEW TIPPASANDARA','Ward',58,'Sumithra Vijaykumar','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'NILASANDRA','Ward',116,'Lokesh','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'OKALIPURAM','Ward',96,'Queen Elezabeth','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'PADARAYANAPURA','Ward',135,'Nazni Begum','Independent');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'PADMANABHA NAGAR','Ward',182,'L.Srinivas','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'PATTABHIRAM NAGAR','Ward',168,'C.K.Ramamurthy','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'PEENYA INDUSTRIAL AREA','Ward',41,'K.L.Thimmananjaiah','Independent');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'PRAKASH NAGAR','Ward',98,'K.Ravindran','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'PULIKESHINAGAR','Ward',78,'Abdul Rakib Zakir','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'PUTTENAHALLI','Ward',187,'L.Ramesh','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'RADHAKRISHNA TEMPLE WARD','Ward',18,'D.Venkatesh','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'RAJAGOPAL NAGAR','Ward',70,'Gangadhar.H.N','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'RAJAJI NAGAR','Ward',99,'H.R.Krishnappa','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'RAJAMAHAL GUTTAHALLI','Ward',64,'M.Vijaya Kumari','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'RAJARAJESHWARI NAGAR','Ward',160,'G.H.Ramachandra','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'RAMAMURTHY NAGAR','Ward',26,'M.Revanna','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'RAMASWAMY PALYA','Ward',62,'Chandra N','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'RAYAPURAM','Ward',137,'C.S.Radha Krishna','JDS');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SAGAYARAPURAM','Ward',60,'Palaniyammal.V','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SAMPANGIRAM NAGAR','Ward',110,'M.Gopi','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SANJAYA NAGAR','Ward',19,'N.M.Krishnamurthy','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SARAKKI','Ward',178,'S.K.Nataraj','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SARVAGNA NAGAR','Ward',79,'J.Bhuvaneshwari','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SHAKAMBARI NAGAR','Ward',179,'B.Somashekar','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SHAKTHI GANAPATHI NAGAR','Ward',74,'Padmavathi Srinivas','JDS');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SHANKAR MATT','Ward',75,'M.Shivaraju','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SHANTALA NAGAR','Ward',111,'Shivakumar .K','Others');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SHANTHI NAGAR','Ward',117,'P.Sowmya','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SHETTIHALLI','Ward',12,'Sharadamma','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SHIVAJI NAGAR','Ward',92,'Farida','Independent');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SHIVANAGARA','Ward',107,'Manjunath','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SIDDAPURA','Ward',144,'M.Udayshankar','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SINGASANDRA','Ward',191,'Kavitha Babu Raj','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'S K GARDEN','Ward',61,'Devika Rani Sridhar','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SRINAGAR','Ward',156,'T.Thimmegowda','JDS');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SRIRAMAMANDIR','Ward',108,'M.G.Jayarathna','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SUBHASH NAGAR','Ward',95,'T.Mallesh','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SUBRAMANYA NAGAR','Ward',66,'Shashikala Kiran S','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SUDDAGUNTE PALYA','Ward',152,'G.Manjunath','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SUDHAM NAGARA','Ward',118,'Avvai .A','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'SUNKENAHALLI','Ward',142,'P.N.Sadashiva','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'T DASARAHALLI','Ward',15,'Puttamma','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'THANISANDRA','Ward',6,'Lalitha','JDS');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'ULLALU','Ward',130,'Rajanna','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'UTTARAHALLI','Ward',184,'Ramesh Raju.K','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'VANNARPET','Ward',115,'Vijayan .S','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'VARTHURU','Ward',149,'S.Uday Kumar','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'VASANTH NAGAR','Ward',93,'Katta Jagadish','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'VASANTHPURA','Ward',197,'Vijaya.A','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'VIDYAPEETA WARD','Ward',164,'M.Venkatesh','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'VIDYARANYAPURA','Ward',9,'Nandini.K','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'VIJAYANAGAR','Ward',123,'Ravindra.H','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'VIJNANA NAGAR','Ward',81,'Geetha Vivekananda','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'VIJNANAPURA','Ward',51,'P.Sugumar','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'VISHVESHWARA PURAM','Ward',143,'Anil Kumar.S','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'VISHWANATH NAGENAHALLI','Ward',22,'Munirathnamma','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'VRISABHAVATHI NAGAR','Ward',102,'L.Nagarathna','JDS');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'YEDIYUR','Ward',167,'Ramesh N.R','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'YELAHANKA SATELLITE TOWN','Ward',4,'M.Muniraju','BJP');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'YELCHENAHALLI','Ward',185,'O.Manjunath','INC');
INSERT INTO tb_electedrep_master (parent,const_ward_name,const_ward_type,elec_comm_code,current_elected_rep,current_elected_party) values(3,'YESHWANTHPURA','Ward',37,'Munirathna','INC');
