INSERT INTO tb_ai_questions values(1,'Anganwadi worker is aware of year of Establishment of this Anganwadi (Ask Anganwadi Worker)');
INSERT INTO tb_ai_questions values(2,'Anganwadi worker was present on the day of the visit');
INSERT INTO tb_ai_questions values(3,'Anganwadi helper was present on the day of the visit');
INSERT INTO tb_ai_questions values(4,'Anganwadi runs in its own building (i.e designated for running Anganwadi,built by the Woman & Child department)');
INSERT INTO tb_ai_questions values(5,'There is a spacious room available in the Anganwadi (for all children as per the norm)(through observation)');
INSERT INTO tb_ai_questions values(6,'There is enough space available for children to play in the Anganwadi premise');
INSERT INTO tb_ai_questions values(7,'Anganwadi Centre premises has lawn, flower plants and trees.(through observation)');
INSERT INTO tb_ai_questions values(8,'Plaster of the walls are not damaged.(through observation)');
INSERT INTO tb_ai_questions values(9,'Plaster of the floor is not damaged (through observation)');
INSERT INTO tb_ai_questions values(10,'Roof of the room is not damaged and not leaking.(through observation)');
INSERT INTO tb_ai_questions values(11,'All doors are strong and can be bolted and locked.(through observation)');
INSERT INTO tb_ai_questions values(12,'All windows are strong and can be bolted and locked.(through observation)');
INSERT INTO tb_ai_questions values(13,'The floor, walls, corners of walls and roof are free of cobweb and dust.(through observation)');
INSERT INTO tb_ai_questions values(14,'Anganwadi Centre wall painted and is full of writings related to Learning.(through observation)');
INSERT INTO tb_ai_questions values(15,'Centre has waste basket (through observation)');
INSERT INTO tb_ai_questions values(16,'Children are using the waste basket (observed on the day of visit )');
INSERT INTO tb_ai_questions values(17,'Children are taught to maintain cleanliness in the room(ask Aya or Worker & observe)');
INSERT INTO tb_ai_questions values(18,'Separate corner is designated for stocking the food supply in the Anganwadi premises(through observation)');
INSERT INTO tb_ai_questions values(19,'Store room is neat and free from dust, waste (protected from rain and wind and is free from pest, worms and rats)');
INSERT INTO tb_ai_questions values(20,'Food was covered and hygiene was maintained.(through observation)');
INSERT INTO tb_ai_questions values(21,'All children got the meals on time on the day of visit (through observation)');
INSERT INTO tb_ai_questions values(22,'The cook maintains cleanliness and wore clean clothes on the day of visit (through observation)');
INSERT INTO tb_ai_questions values(23,'Centre has separate place to handwash after the meal for children (through observation)');
INSERT INTO tb_ai_questions values(24,'Center has water tap (through observation)');
INSERT INTO tb_ai_questions values(25,'There is regular water supply in the tap (through observation)');
INSERT INTO tb_ai_questions values(26,'surrounding of the water tap is clean (through observation)');
INSERT INTO tb_ai_questions values(27,'Clean drinking water is stored in clean vessels (through observation)');
INSERT INTO tb_ai_questions values(28,'The vessel is always kept covered and children do not dip their hands/fingers in it(through observation).');
INSERT INTO tb_ai_questions values(29,'There is a toilet (through observation)');
INSERT INTO tb_ai_questions values(30,'Toilet roof protects children from rain and heat. (through observation)');
INSERT INTO tb_ai_questions values(31,'Running water is available in the toilet tap(through observation)');
INSERT INTO tb_ai_questions values(32,'There is a mug in the toilet and reachable to children (through observation)');
INSERT INTO tb_ai_questions values(33,'The toilet’s interior and the basin are free of stink and moss. (through observation)');
INSERT INTO tb_ai_questions values(34,'First aid box with all necessary items available (through observation)');
INSERT INTO tb_ai_questions values(35,'Materials available in first aid box are being used (ask Aya or Worker & observe)');
INSERT INTO tb_ai_questions values(36,'Black board is being used (Through observation)');
INSERT INTO tb_ai_questions values(37,'Black board is convenient for children and teachers’ viewing and writing.(Through observation)');
INSERT INTO tb_ai_questions values(38,'Admission records are maintained');
INSERT INTO tb_ai_questions values(39,'The Anganwadi worker daily signs and confirms that children’s attendance is as per the attendance register.');
INSERT INTO tb_ai_questions values(40,'Name of the student who has taken TC is circled and comment written (to be cross checked)');
INSERT INTO tb_ai_questions values(41,'Anganwadi worker has maintained the document on all the children who have passed out of Anganwadi last year and in aware of their whereabouts(to be cross checked)');
INSERT INTO tb_ai_questions values(42,'50% of the children enrolled were present on the day of visit ((to be cross checked))');
INSERT INTO tb_ai_questions values(43,'Progress records are maintained');
INSERT INTO tb_ai_questions values(44,'Teachers’ diary is maintained');
INSERT INTO tb_ai_questions values(45,'Anaganwadi worker maintains the attendance register of the Anganwadi staff(to be asked to Anganwadi Worker & cross check it)');
INSERT INTO tb_ai_questions values(46,'Accounts are maintained (to be asked to Anganwadi Worker & cross check it)');
INSERT INTO tb_ai_questions values(47,'Stock register of the Teach Learning Material is maintained (to be asked to Anganwadi Worker & cross check it)');
INSERT INTO tb_ai_questions values(48,'Anganwadi has a record of health details of each children (ask Aya or Worker & cross check records)');
INSERT INTO tb_ai_questions values(49,'Health checkup was held last month (ask Aya or Worker & cross check records)');
INSERT INTO tb_ai_questions values(50,'Anganwadi has a list of children with special needs(through observation)');
INSERT INTO tb_ai_questions values(51,'A slope is available for physically challenged / disabled children to use. (through observation)');
INSERT INTO tb_ai_questions values(52,'Materials necessary (learning) for physically challenged / disabled children are available. (ask Aya or Worker & cross check records)');
INSERT INTO tb_ai_questions values(53,'Teacher is Trained to teach physically challenged / disabled children (ask Aya or Worker )');
INSERT INTO tb_ai_questions values(54,'Bal Vikas Samithi exists.(ask Aya or Worker )');
INSERT INTO tb_ai_questions values(55,'Has maintained the roster of members.(ask Aya or Worker & cross check records)');
INSERT INTO tb_ai_questions values(56,'BVS proceedings book exists (ask Aya or Worker & cross check records)');
INSERT INTO tb_ai_questions values(57,'Anganwadi Centre has a list of roles and responsibilities of BVS as prescribed by the Govt(ask Aya or Worker & cross check records)');
INSERT INTO tb_ai_questions values(58,'BVS meeting held as per the norm (ask Aya or Worker & cross check records)');
INSERT INTO tb_ai_questions values(59,'Friends of Anganwadi has been formed (ask Akshara FC & cross check with FoA members)');
INSERT INTO tb_ai_questions values(60,'Friends of Anganwadi members are conducting the activities(ask Akshara FC & cross check with FoA members)');
INSERT INTO tb_ai_questions values(61,'Anganwadi worker has already got all the necessary training to become effective Anganwadi workers(ask Anganwadi worker)');
INSERT INTO tb_ai_questions values(62,'The Anganwadi calendar has been prepared(ask Anganwadi worker cross check records)');
INSERT INTO tb_ai_questions values(63,'Anganwadi has Akshara Anganwadi Centre Preparedness kit (through observation)');
INSERT INTO tb_ai_questions values(64,'Anganwadi worker has been trained on the kit(ask Worker & cross check )');
INSERT INTO tb_ai_questions values(65,'Anganwadi worker has been trained on Assessment of the children(ask Worker & cross check )');
INSERT INTO tb_ai_questions values(66,'Child Assessment has trained by Akshara has taken place (ask Aya or Worker & cross check records)');
INSERT INTO tb_ai_questions values(67,'Children are engaged with materials based on learning outcomes are used by children (Through observation)');
INSERT INTO tb_ai_questions values(68,'Anganwadi worker gives needed guidance to each child ,examines all activities, correct mistakes (Through observation).');
INSERT INTO tb_ai_questions values(69,'Anganwadi worker uses the Akshara Kit(through observation)');
INSERT INTO tb_ai_questions values(70,'Material usage is learning outcome based and effective(Through Observation)');
